version: '4.9'

services:
#Mongo Container
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
  
  #Node Container
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGODB_CONNECTION_URL=mongodb://mongo_db:27017/task-manager
      - WEB_TOKEN_SECRET=anytextjusttocreatetokenforauthentication
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}
     

    
